name: farmsmart_flutter
description: Farmsmart Flutter app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.0+20
  image_cropper: ^1.0.2

  flutter_localizations:
    sdk: flutter

  intl_translation: ^0.17.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  flutter_html:
    git:
      url: https://github.com/farmsmart/flutter_html.git
      ref: feature/customImgRender 
  flutter_launcher_icons: ^0.7.0
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.6
  cloud_functions: ^0.5.0
  firebase_dynamic_links: ^0.5.0+11

  webview_flutter: ^0.3.6
  share: ^0.6.1+1
  package_info: ^0.4.0+3
  cached_network_image: ^2.2.0+1
  url_launcher: ^5.1.1
  decimal: ^0.3.0

  json_serializable: ^2.0.0

  mockito: ^4.1.0


dev_dependencies:
  test:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/chatbot_avatar.png
    - assets/icons/app_icon.png
    - assets/icons/community_selected.png
    - assets/icons/community.png
    - assets/icons/discover_selected.png
    - assets/icons/discover.png
    - assets/icons/my_plot_selected.png
    - assets/icons/my_plot.png
    - assets/icons/profit_loss_selected.png
    - assets/icons/profit_loss.png
    - assets/icons/detail_icon_date.png
    - assets/icons/detail_icon_description.png
    - assets/privacy_policy.html
    - assets/icons/profit_add.png
    - assets/icons/tick_large.png
    - assets/icons/detail_icon_companion.png
    - assets/icons/detail_icon_complexity.png
    - assets/icons/detail_icon_crop_type.png
    - assets/icons/detail_icon_non_companion.png
    - assets/icons/detail_icon_profitability.png
    - assets/icons/detail_icon_setup_costs.png
    - assets/icons/detail_icon_water.png
    - assets/privacy_policy.html
    - assets/icons/flag_kenya.png
    - assets/icons/flag_usa.png
    - assets/icons/detail_icon_sale.png
    - assets/icons/detail_icon_cost.png
    - assets/icons/radio_button_default.png
    - assets/icons/radio_button_active.png
    - assets/icons/chevron.png
    - assets/icons/detail_icon_best_soil.png
    - assets/icons/detail_icon_invite.png
    - assets/icons/detail_icon_language.png
    - assets/icons/detail_icon_new_profile.png
    - assets/icons/detail_icon_pin.png
    - assets/raw/
    - assets/icons/
    - assets/icons/nav_icon_back.png
    - assets/icons/nav_icon_options.png
    - assets/icons/nav_icon_cancel.png
    - assets/responses/create_account_mock_form.json
    - assets/responses/farmsmart_chat_ui_flow.json
    - assets/responses/farmsmart_chat_ui_flow_sw.json

  fonts:
  - family: IBMPlexSans
    fonts:
      - asset: assets/fonts/IBMPlexSans-Bold.ttf
      - asset: assets/fonts/IBMPlexSans-Medium.ttf
      - asset: assets/fonts/IBMPlexSans-Regular.ttf


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon_v2.png"

  # To update the app icon check https://pub.dartlang.org/packages/flutter_launcher_icons

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
